# Modified by Longbridge for gpui-fast publication.
[package]
name = "gpui-fast-wgpu"
version = "0.1.7"
edition = "2024"
publish = ["crates-io"]
license = "Apache-2.0"
repository = "https://github.com/longbridge/gpui-fast"
homepage = "https://github.com/longbridge/gpui-fast"
readme = "README.md"
documentation = "https://docs.rs/gpui-fast-wgpu/0.1.7/gpui_wgpu/"
description = "gpui_wgpu: GPUI with gpui-fast rendering and layout optimizations"
autoexamples = false
autobenches = false
autotests = false
authors = ["Longbridge"]
include = ["/src/**", "/resources/**", "/build.rs", "/Cargo.toml", "/README.md", "/LICENSE", "/NOTICE"]

[lib]
path = "src/gpui_wgpu.rs"
doctest = false
name = "gpui_wgpu"

[features]
default = []
bench-support = ["gpui/bench-support", "dep:image"]
font-kit = ["dep:font-kit"]
test-support = ["gpui/test-support", "dep:image"]

[dependencies]
cosmic-text = "0.19.0"

[dependencies.gpui]
default-features = false
package = "gpui-fast"
version = "^0.1.7"
path = "../gpui"

[dependencies.anyhow]
version = "1.0.86"

[dependencies.bytemuck]
version = "1"

[dependencies.collections]
version = "=0.3.8"
package = "gpui-pre-collections"

[dependencies.etagere]
version = "0.2"

[dependencies.itertools]
version = "0.14.0"

[dependencies.image]
version = "0.25.1"
default-features = false
features = ["bmp", "dds", "exr", "ff", "gif", "hdr", "ico", "jpeg", "png", "pnm", "qoi", "rayon", "tga", "tiff", "webp"]
optional = true

[dependencies.log]
version = "0.4"
default-features = false
features = ["std"]

[dependencies.parking_lot]
version = "0.12.1"

[dependencies.profiling]
version = "1"

[dependencies.raw-window-handle]
version = "0.6"

[dependencies.smallvec]
version = "1.6"
features = ["union", "const_new"]

[dependencies.swash]
version = "0.2.6"

[dependencies.unicode-bidi]
version = "0.3.18"
default-features = false
features = ["hardcoded-data"]

[dependencies.unicode-segmentation]
version = "1.10"

[dependencies.gpui_util]
package = "gpui-pre-util"
version = "=0.3.8"

[dependencies.font-kit]
package = "zed-font-kit"
version = "0.14.1-zed"
default-features = false
optional = true

[target."cfg(any(target_os = \"linux\", target_os = \"freebsd\"))".dependencies.wgpu]
version = "29.0"
default-features = false
features = ["std", "parking_lot", "metal", "gles", "vulkan", "wgsl", "webgpu"]

[target."cfg(not(any(target_os = \"linux\", target_os = \"freebsd\")))".dependencies.wgpu]
version = "29.0"
default-features = true

[target."cfg(target_family = \"wasm\")".dependencies.web-sys]
version = "0.3"
features = ["HtmlCanvasElement"]

[target."cfg(target_family = \"wasm\")".dependencies.wgpu]
version = "29.0"
default-features = false
features = ["webgl"]

[lints.rust.unexpected_cfgs]
level = "allow"
